# Generated by Django 5.2.1 on 2025-06-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_remove_topic_grade_topic_grades_alter_topic_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='grades',
            field=models.ManyToManyField(related_name='grades', to='materials.grade'),
        ),
    ]
